### ISSUE TITLE
...is not a valid Win32 application...

### ISSUE THREAD

**Issue by HallofFamer** [Crack/runkit-windows#2]
I downloaded the php 5.5 thread safe runkit to my local drive and try to add it to the phi.ini of my wamp server, and then I got this error:

[12-Feb-2015 23:41:31 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'D:/Development/WAMP/bin/php/php5.5.12/ext/php_runkit.dll' - %1 is not a valid Win32 application.
 in Unknown on line 0

It seems that the file is invalid or corrupted? Why does not it work with my PHP on wampserver? Maybe it has something to do with wampserver itself?

**Comment by Crack** [comment]
Which version of wampserver? AFAIR my runkit modules are 32-bit, so if you are using 64-bit version of wampserver please try with 32-bit.

If it still won't work, please write which exact version of wampserver are you using, and which runkit DLL have you downloaded.

**Comment by HallofFamer** [comment]
well mine is 64 bit, I guess this is the reason why.

**Comment by Crack** [comment]
I will try to look into it, and compile for PHP 5.6 while I'm at it, but it may take some time. For now you can try with 32-bit wampserver, and maybe poke its developers to include runkit.
